// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSxH0Pr6ip8qFqNmEL5Pn7yqVTttibKKc',
    appId: '1:364495813911:web:0a0b25c5eae677ca214b52',
    messagingSenderId: '364495813911',
    projectId: 'city-taxi-93be1',
    authDomain: 'city-taxi-93be1.firebaseapp.com',
    storageBucket: 'city-taxi-93be1.appspot.com',
    measurementId: 'G-4F9CXQQ488',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWVggAL03kp1_-rbaBUL0KQvMnNBffn5U',
    appId: '1:364495813911:android:64ae2bad2b748aad214b52',
    messagingSenderId: '364495813911',
    projectId: 'city-taxi-93be1',
    storageBucket: 'city-taxi-93be1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAujp0uPjeZON2qxLyoXwkMskgEqfdm-Ns',
    appId: '1:364495813911:ios:c52bd4eaf141bd1a214b52',
    messagingSenderId: '364495813911',
    projectId: 'city-taxi-93be1',
    storageBucket: 'city-taxi-93be1.appspot.com',
    iosBundleId: 'com.example.citytaxi',
  );
}
